geo $is_trusted_nginx {
    default 0;
    172.28.0.11/32 1;
    172.28.0.12/32 1;
    172.28.0.13/32 1;
}

map "$is_trusted_nginx:$http_x_forwarded_for" $safe_x_forwarded_for {
    "~^1:(.+)" "$1, $server_addr";
    default "$remote_addr, $server_addr";
}
